import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:revoked_app/core/services/crypto_service.dart';

/// The client signs and the Go server verifies, so the two must agree on the
/// digest. They did not: ecSign defaults to SHA-1/ECDSA while
/// `util/signature.go` hashes with SHA-256, and every identity signature was
/// rejected. These tests pin the agreement.
void main() {
  final crypto = CryptoService();

  test('signs with the digest the server verifies', () {
    expect(CryptoService.ecdsaAlgorithm, 'SHA-256/ECDSA');
  });

  test('a signature verifies under its own public key', () {
    final identity = crypto.generateIdentity(commonName: 'test');
    const message = 'challenge-nonce';

    final signature = crypto.signWithPrivateKey(
      privateKeyPem: identity.privateKeyPem,
      message: message,
    );

    expect(
      crypto.verifySignature(
        publicKeyPem: identity.publicKeyPem,
        message: message,
        signatureBytes: base64.decode(signature),
      ),
      isTrue,
    );
  });

  test('a signature does not verify for a different message', () {
    final identity = crypto.generateIdentity(commonName: 'test');
    final signature = crypto.signWithPrivateKey(
      privateKeyPem: identity.privateKeyPem,
      message: 'the-real-nonce',
    );

    expect(
      crypto.verifySignature(
        publicKeyPem: identity.publicKeyPem,
        message: 'a-substituted-nonce',
        signatureBytes: base64.decode(signature),
      ),
      isFalse,
    );
  });

  test(
    'verifies an RSA signature, which is what a server root key produces',
    () {
      // Generated by cmd/revoked/server (RSA-2048, PKCS1v15 over SHA-256). An
      // EC-only verifier reports every one of these as invalid, which made the
      // domain check declare honest peers spoofed.
      final fixture = File('test/fixtures/rsa_signature.json');
      if (!fixture.existsSync()) {
        markTestSkipped('run tool/gen_rsa_fixture.sh to refresh the fixture');
        return;
      }
      final data =
          jsonDecode(fixture.readAsStringSync()) as Map<String, dynamic>;

      expect(
        crypto.verifySignature(
          publicKeyPem: data['publicKeyPem'] as String,
          message: data['message'] as String,
          signatureBytes: _hex(data['signatureHex'] as String),
        ),
        isTrue,
      );
    },
  );
}

Uint8List _hex(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}
